version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.14.3
    steps:
      - checkout
      - run:
          name: terraform init & validate
          command: |
            terraform init examples/single-cluster
            terraform validate examples/single-cluster
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan:
    docker:
      - image: hashicorp/terraform:0.14.3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform plan
          command: |
            terraform plan \
              -var client_id=$ARM_CLIENT_ID \
              -var client_secret=$ARM_CLIENT_SECRET \
              -var key_vault_policy_object_ids='{}' \
              -var infra_name="k8s-infra" \
              -var-file config/ci.tfvars \
              examples/single-cluster

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - plan:
          requires:
            - build
          context:
            - azure-credentials