## Global Config
global:
  infraName: k8s-infra 
  ## The project environment to run with: can be dev, tst, acc, staging, prd, etc...
  environment: lab
  ## Enable a bastion instance
  bastionEnabled: false
  ## Bastion admin user
  bastionAdminUser: kubebastionadmin
  ## The Azure location of the resources
  azLocation: "north europe"

## Keyvault config
## Each cluster will have its own keyvault next to it
keyvault:
  ## Keyvault Key Permissions
  keyPermissions:
    - "create"
    - "get"
    - "list"
    - "delete"

  ## Keyvault Secret Permissions
  secretPermissions:
    - "set"
    - "get"
    - "list"
    - "delete"

  ## Keyvault Certificate Permissions
  certificatePermissions:
    - "create"
    - "update"
    - "get"
    - "list"
    - "delete"

  ## Keyvault Storage Permissions
  storagePermissions:
    - "update"
    - "get"
    - "list"
    - "delete"

## List of clusters to deploy
clusters:
    ## the cluster name
  - name: main
    ## The subnet in which this cluster will be added to
    ## The subnet must be created as part of the infra part
    subnetName: main
    ## If false, the resource will not be deployed
    enabled: true
    ## Whether the dashboard is enabled
    kubeDashboardEnabled: true
    ## By enabling this option, the API server will only be accessable within the VNET
    ## Check here on how to conncet to a private cluster:
    ## https://docs.microsoft.com/en-us/azure/aks/private-clusters#options-for-connecting-to-the-private-cluster
    privateClusterEnabled: false
    ## Enable scaling for nodes
    autoScalingEnabled: true
    ## The kubernetes Version
    clusterVersion: "1.18.8"  
    clusterAdminUser: mainadmin
    clusterNetwork:
      networkPlugin: azure
      networkPolicy: calico
      serviceCidr: "10.100.0.0/16"
      dockerBridgeCidr: "172.17.0.1/16"
      dnsServiceIP: "10.100.0.10"
      loadBalancerSKU: Standard
    ## Active directory integration
    activeDirectory:
      rbac:
        enabled: true
    defaultNodePool:
      name: "d4v3"
      nodeCount: 2
      vmSize: "Standard_D4_v3"
      diskSizeGB: 30
      minCount: 1
      maxCount: 6
      maxPods: 110
      availabilityZones: 
        - "1"
    ## 
    adAdminsObjectIds:
      - 00000000-0000-0000-0000-000000000000

    ## key vault policy object ids that will be added to the keyvault access policies
    keyvault:
      policyObjectIds:
        - name: sp ## The Service principal Object ID
          value: "00000000-0000-0000-0000-000000000000"

nodePools: []
  # - key: "mediumSize"
  #   clusterName: "main"
  #   subnetName: "main"
  #   name: b2s
  #   nodeCount: 2
  #   vmSize: "Standard_B2s"
  #   diskSizeGB: 30
  #   minCount: 1
  #   maxCount: 6
  #   maxPods: 110
  #   availabilityZones: 
  #     - "1"
  #   osType: "Linux"
  #   autoScalingEnabled: true

## Additional Tags to be attached to the resources
tags:
  - key: provisioner
    value: terraform
  - key: owner
    value: devops-team
  - key: contact
    value: ibraheemalsaady
  - key: costCenter
    value: finance-123